name: frontend

on: push

jobs:
    build-push-frontend-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: thunderspike/645_assignment3_frontend:latest

    redeploy-rancher-middleware-workload:
        needs: build-push-frontend-image
        runs-on: ubuntu-latest
        steps:
            - name: Github Action for curl
              uses: wei/curl@v1.1.1
              with:
                  args: >
                      -k
                      -u "${{ secrets.RANCHER_TOKEN }}"
                      -X POST
                      -H 'Accept: application/json'
                      -H 'Content-Type: application/json'
                      https://100.27.49.189/v3/project/c-6d94r:p-bw2l4/workloads/deployment:hw3:frontend?action=redeploy
